//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICalculator")]
public interface ICalculator
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/GetConnenctionToDB", ReplyAction="http://tempuri.org/ICalculator/GetConnenctionToDBResponse")]
    string GetConnenctionToDB();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/GetConnenctionToDB", ReplyAction="http://tempuri.org/ICalculator/GetConnenctionToDBResponse")]
    System.Threading.Tasks.Task<string> GetConnenctionToDBAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/CheckLogin", ReplyAction="http://tempuri.org/ICalculator/CheckLoginResponse")]
    string CheckLogin(string userName, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/CheckLogin", ReplyAction="http://tempuri.org/ICalculator/CheckLoginResponse")]
    System.Threading.Tasks.Task<string> CheckLoginAsync(string userName, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/AddNewUser", ReplyAction="http://tempuri.org/ICalculator/AddNewUserResponse")]
    string AddNewUser(string userName, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/AddNewUser", ReplyAction="http://tempuri.org/ICalculator/AddNewUserResponse")]
    System.Threading.Tasks.Task<string> AddNewUserAsync(string userName, string password);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalculatorChannel : ICalculator, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculatorClient : System.ServiceModel.ClientBase<ICalculator>, ICalculator
{
    
    public CalculatorClient()
    {
    }
    
    public CalculatorClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetConnenctionToDB()
    {
        return base.Channel.GetConnenctionToDB();
    }
    
    public System.Threading.Tasks.Task<string> GetConnenctionToDBAsync()
    {
        return base.Channel.GetConnenctionToDBAsync();
    }
    
    public string CheckLogin(string userName, string password)
    {
        return base.Channel.CheckLogin(userName, password);
    }
    
    public System.Threading.Tasks.Task<string> CheckLoginAsync(string userName, string password)
    {
        return base.Channel.CheckLoginAsync(userName, password);
    }
    
    public string AddNewUser(string userName, string password)
    {
        return base.Channel.AddNewUser(userName, password);
    }
    
    public System.Threading.Tasks.Task<string> AddNewUserAsync(string userName, string password)
    {
        return base.Channel.AddNewUserAsync(userName, password);
    }
}
